### ISSUE TITLE
Develop Umm Al Qura(Hijri) Datepicker module for use in the solar calendar for Odoo 12

### ISSUE THREAD

**Issue by movahhed** [salsowelim/odoo_hijri_datepicker#2]
hi

**Comment by movahhed** [comment]
Hello to all developer friends
Let's turn a calendar and data selector together in Odoo 12 to Hijri Shamsi ...
Are yo ready !?

**Comment by movahhed** [comment]
The JavaScript codes used for this are as follows:
https://github.com/Mds92/MD.BootstrapPersianDateTimePicker

https://github.com/jalaali/moment-jalaali

https://www.odoo.com/forum/help-1/question/how-to-change-the-date-calendar-widget-to-support-solar-hijri-calendar-50209

**Comment by movahhed** [comment]
I ask Suliman Alsowelim to help us. Thanks

**Comment by movahhed** [comment]
https://www.jqueryscript.net/time-clock/Persian-Jalali-Calendar-Data-Picker-Plugin-With-jQuery-kamaDatepicker.html

**Comment by movahhed** [comment]
Dear Suliman
You are in your module from JQuery http://keith-wood.name/calendarsRef.html
You have used that js for the persian calendar.
Can you change your code to the solar calendar, even for version 11 of Odoo?
After that, I will migrating to 12

**Comment by salsowelim** [comment]
Sorry, off topic. You can create/fork another repository for this. Good luck.
